# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift-version: ["6.0.1"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -q
    - name: Run tests
      run: swift test -q

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Run linter
      run: swiftformat --config rules.swiftformat .
    - name: Verify that `swiftformat --config rules.swiftformat .` did not change outputs (if it did, please re-run it and re-commit!)
      run: git diff --exit-code